// Paires de mots : [mot civil, mot undercover]. Les rôles sont tirés au hasard
// dans un sens ou dans l'autre à chaque partie.
const WORD_CATEGORIES = {
  "Nourriture": [
    ["Pizza", "Quiche"], ["Burger", "Sandwich"], ["Croissant", "Pain au chocolat"],
    ["Pâtes", "Riz"], ["Sushi", "Maki"], ["Crêpe", "Gaufre"], ["Frites", "Chips"],
    ["Ketchup", "Mayonnaise"], ["Moutarde", "Wasabi"], ["Beurre", "Margarine"],
    ["Fromage", "Yaourt"], ["Camembert", "Brie"], ["Raclette", "Fondue"],
    ["Tartiflette", "Gratin dauphinois"], ["Kebab", "Tacos"], ["Hot-dog", "Croque-monsieur"],
    ["Soupe", "Velouté"], ["Omelette", "Œuf au plat"], ["Steak", "Côtelette"],
    ["Saucisson", "Jambon"], ["Poulet", "Dinde"], ["Saumon", "Thon"],
    ["Crevette", "Langoustine"], ["Huître", "Moule"], ["Couscous", "Paella"],
    ["Lasagnes", "Cannellonis"], ["Ravioli", "Gnocchi"], ["Salade", "Taboulé"],
    ["Baguette", "Pain de mie"], ["Brioche", "Pain au lait"], ["Muffin", "Cupcake"],
    ["Cookie", "Brownie"], ["Macaron", "Meringue"], ["Éclair", "Religieuse"],
    ["Tiramisu", "Panna cotta"], ["Mousse au chocolat", "Crème brûlée"],
    ["Glace", "Sorbet"], ["Donut", "Beignet"], ["Nutella", "Confiture"],
    ["Miel", "Sirop d'érable"], ["Sucre", "Sel"], ["Poivre", "Piment"],
    ["Céréales", "Muesli"], ["Pop-corn", "Cacahuètes"], ["Bonbon", "Chewing-gum"],
    ["Chocolat noir", "Chocolat au lait"], ["Tarte aux pommes", "Clafoutis"],
    ["Bûche de Noël", "Galette des rois"], ["Ramen", "Pho"], ["Burrito", "Fajitas"],
    ["Guacamole", "Houmous"], ["Nuggets", "Cordon bleu"], ["Bolognaise", "Carbonara"],
    ["Purée", "Gratin"], ["Quinoa", "Boulgour"], ["Tofu", "Seitan"],
    ["Hachis parmentier", "Moussaka"], ["Pot-au-feu", "Blanquette"],
    ["Bœuf bourguignon", "Coq au vin"], ["Cassoulet", "Choucroute"],
    ["Escargot", "Cuisses de grenouille"], ["Foie gras", "Pâté"], ["Bagel", "Wrap"],
    ["Mozzarella", "Burrata"], ["Parmesan", "Comté"], ["Roquefort", "Gorgonzola"],
    ["Chantilly", "Crème fraîche"], ["Caramel", "Praliné"], ["Madeleine", "Financier"],
    ["Calisson", "Nougat"], ["Barbe à papa", "Pomme d'amour"], ["Pancake", "Blini"],
  ],
  "Fruits & légumes": [
    ["Pomme", "Poire"], ["Orange", "Mandarine"], ["Citron", "Citron vert"],
    ["Fraise", "Framboise"], ["Cerise", "Groseille"], ["Banane", "Plantain"],
    ["Pêche", "Abricot"], ["Melon", "Pastèque"], ["Raisin", "Myrtille"],
    ["Ananas", "Mangue"], ["Kiwi", "Fruit de la passion"], ["Noix de coco", "Avocat"],
    ["Prune", "Figue"], ["Pamplemousse", "Clémentine"], ["Litchi", "Grenade"],
    ["Tomate", "Poivron"], ["Carotte", "Navet"], ["Courgette", "Concombre"],
    ["Aubergine", "Courge"], ["Potiron", "Citrouille"], ["Pomme de terre", "Patate douce"],
    ["Oignon", "Échalote"], ["Ail", "Gingembre"], ["Brocoli", "Chou-fleur"],
    ["Épinard", "Blette"], ["Laitue", "Roquette"], ["Petit pois", "Haricot vert"],
    ["Champignon", "Truffe"], ["Maïs", "Blé"], ["Radis", "Betterave"],
    ["Poireau", "Céleri"], ["Artichaut", "Asperge"], ["Lentille", "Pois chiche"],
    ["Noisette", "Amande"], ["Noix", "Noix de cajou"], ["Olive", "Câpre"],
    ["Basilic", "Persil"], ["Menthe", "Coriandre"], ["Chou de Bruxelles", "Endive"],
    ["Mûre", "Cassis"],
  ],
  "Boissons": [
    ["Café", "Thé"], ["Coca", "Pepsi"], ["Bière", "Cidre"], ["Vin rouge", "Vin blanc"],
    ["Champagne", "Prosecco"], ["Whisky", "Rhum"], ["Vodka", "Gin"], ["Tequila", "Mezcal"],
    ["Mojito", "Caïpirinha"], ["Sangria", "Punch"], ["Jus d'orange", "Jus de pomme"],
    ["Limonade", "Sprite"], ["Eau plate", "Eau gazeuse"], ["Lait", "Lait d'amande"],
    ["Chocolat chaud", "Cappuccino"], ["Expresso", "Latte"], ["Smoothie", "Milkshake"],
    ["Red Bull", "Monster"], ["Ice tea", "Thé glacé"], ["Pastis", "Ricard"],
    ["Spritz", "Martini"], ["Kir", "Rosé"], ["Sirop", "Grenadine"], ["Tisane", "Infusion"],
    ["Bubble tea", "Frappuccino"], ["Saké", "Soju"], ["Cognac", "Armagnac"],
    ["Jägermeister", "Get 27"], ["Orangina", "Fanta"], ["Kombucha", "Kéfir"],
  ],
  "Animaux": [
    ["Chat", "Chien"], ["Lion", "Tigre"], ["Loup", "Renard"], ["Cheval", "Âne"],
    ["Vache", "Taureau"], ["Mouton", "Chèvre"], ["Cochon", "Sanglier"],
    ["Lapin", "Lièvre"], ["Souris", "Rat"], ["Hamster", "Cochon d'Inde"],
    ["Dauphin", "Baleine"], ["Requin", "Orque"], ["Pieuvre", "Calamar"],
    ["Crabe", "Homard"], ["Aigle", "Faucon"], ["Hibou", "Chouette"],
    ["Pigeon", "Mouette"], ["Corbeau", "Pie"], ["Perroquet", "Toucan"],
    ["Pingouin", "Manchot"], ["Canard", "Oie"], ["Poule", "Coq"],
    ["Serpent", "Lézard"], ["Crocodile", "Alligator"], ["Tortue", "Escargot"],
    ["Grenouille", "Crapaud"], ["Abeille", "Guêpe"], ["Papillon", "Libellule"],
    ["Fourmi", "Termite"], ["Araignée", "Scorpion"], ["Moustique", "Mouche"],
    ["Éléphant", "Rhinocéros"], ["Girafe", "Zèbre"], ["Singe", "Gorille"],
    ["Ours", "Panda"], ["Kangourou", "Koala"], ["Chameau", "Dromadaire"],
    ["Cerf", "Élan"], ["Écureuil", "Castor"], ["Hérisson", "Porc-épic"],
    ["Chauve-souris", "Hibou"], ["Méduse", "Étoile de mer"], ["Phoque", "Otarie"],
    ["Guépard", "Léopard"], ["Hyène", "Chacal"], ["Flamant rose", "Cigogne"],
    ["Paon", "Dinde"], ["Coccinelle", "Scarabée"], ["Ver de terre", "Limace"],
    ["Poisson rouge", "Piranha"], ["Licorne", "Pégase"], ["Dragon", "Phénix"],
    ["Hippopotame", "Morse"], ["Mammouth", "Dinosaure"], ["Lama", "Alpaga"],
  ],
  "Maison & objets": [
    ["Canapé", "Fauteuil"], ["Lit", "Hamac"], ["Chaise", "Tabouret"],
    ["Table", "Bureau"], ["Armoire", "Commode"], ["Lampe", "Bougie"],
    ["Oreiller", "Coussin"], ["Couverture", "Couette"], ["Rideau", "Store"],
    ["Fenêtre", "Porte"], ["Escalier", "Ascenseur"], ["Douche", "Baignoire"],
    ["Lavabo", "Évier"], ["Frigo", "Congélateur"], ["Four", "Micro-ondes"],
    ["Grille-pain", "Gaufrier"], ["Cafetière", "Bouilloire"], ["Poêle", "Casserole"],
    ["Fourchette", "Cuillère"], ["Couteau", "Ciseaux"], ["Assiette", "Bol"],
    ["Verre", "Tasse"], ["Brosse à dents", "Peigne"], ["Savon", "Shampoing"],
    ["Serviette", "Peignoir"], ["Aspirateur", "Balai"], ["Lave-linge", "Lave-vaisselle"],
    ["Fer à repasser", "Sèche-cheveux"], ["Miroir", "Tableau"], ["Horloge", "Montre"],
    ["Réveil", "Alarme"], ["Clé", "Cadenas"], ["Parapluie", "Imperméable"],
    ["Sac à dos", "Valise"], ["Portefeuille", "Porte-monnaie"], ["Stylo", "Crayon"],
    ["Gomme", "Taille-crayon"], ["Cahier", "Carnet"], ["Livre", "Magazine"],
    ["Enveloppe", "Colis"], ["Scotch", "Colle"], ["Marteau", "Tournevis"],
    ["Clou", "Vis"], ["Échelle", "Escabeau"], ["Ampoule", "Néon"],
    ["Briquet", "Allumette"], ["Bouteille", "Gourde"], ["Tapis", "Paillasson"],
    ["Poubelle", "Recyclage"], ["Boîte aux lettres", "Sonnette"], ["Vase", "Pot de fleurs"],
    ["Cheminée", "Radiateur"], ["Ventilateur", "Climatiseur"], ["Coffre-fort", "Tirelire"],
    ["Cintre", "Porte-manteau"], ["Lunettes", "Lentilles"], ["Mouchoir", "Papier toilette"],
  ],
  "Vêtements & mode": [
    ["T-shirt", "Chemise"], ["Pull", "Sweat"], ["Jean", "Jogging"], ["Short", "Bermuda"],
    ["Jupe", "Robe"], ["Veste", "Manteau"], ["Doudoune", "Parka"], ["Blouson", "Gilet"],
    ["Basket", "Mocassin"], ["Botte", "Bottine"], ["Tong", "Sandale"], ["Talon", "Escarpin"],
    ["Chaussette", "Collant"], ["Caleçon", "Slip"], ["Soutien-gorge", "Brassière"],
    ["Pyjama", "Nuisette"], ["Casquette", "Bonnet"], ["Chapeau", "Béret"],
    ["Écharpe", "Foulard"], ["Gants", "Moufles"], ["Ceinture", "Bretelles"],
    ["Cravate", "Nœud papillon"], ["Costume", "Smoking"], ["Maillot de bain", "Bikini"],
    ["Collier", "Bracelet"], ["Bague", "Boucle d'oreille"], ["Sac à main", "Pochette"],
    ["Lunettes de soleil", "Masque de ski"], ["Parfum", "Déodorant"], ["Rouge à lèvres", "Gloss"],
    ["Mascara", "Eye-liner"], ["Vernis", "Faux ongles"], ["Tatouage", "Piercing"],
    ["Perruque", "Extensions"], ["Kimono", "Toge"], ["Uniforme", "Déguisement"],
    ["Polo", "Débardeur"], ["Salopette", "Combinaison"], ["Crocs", "Claquettes"],
  ],
  "Lieux": [
    ["Plage", "Piscine"], ["Montagne", "Colline"], ["Forêt", "Jungle"], ["Désert", "Savane"],
    ["Lac", "Étang"], ["Rivière", "Fleuve"], ["Île", "Presqu'île"], ["Volcan", "Geyser"],
    ["Grotte", "Tunnel"], ["Cascade", "Fontaine"], ["Ville", "Village"],
    ["Château", "Palais"], ["Église", "Cathédrale"], ["Mosquée", "Temple"],
    ["Musée", "Galerie"], ["Cinéma", "Théâtre"], ["Bibliothèque", "Librairie"],
    ["École", "Université"], ["Hôpital", "Clinique"], ["Pharmacie", "Herboristerie"],
    ["Supermarché", "Épicerie"], ["Boulangerie", "Pâtisserie"], ["Boucherie", "Poissonnerie"],
    ["Restaurant", "Fast-food"], ["Bar", "Boîte de nuit"], ["Café", "Salon de thé"],
    ["Hôtel", "Auberge"], ["Camping", "Gîte"], ["Aéroport", "Gare"],
    ["Port", "Marina"], ["Métro", "Tramway"], ["Parking", "Garage"],
    ["Banque", "Bureau de poste"], ["Prison", "Commissariat"], ["Tribunal", "Mairie"],
    ["Stade", "Gymnase"], ["Zoo", "Aquarium"], ["Parc d'attractions", "Fête foraine"],
    ["Cirque", "Cabaret"], ["Ferme", "Ranch"], ["Jardin", "Potager"],
    ["Cimetière", "Crypte"], ["Phare", "Tour de contrôle"], ["Usine", "Entrepôt"],
    ["Laverie", "Pressing"], ["Salle de sport", "Spa"], ["Casino", "Bowling"],
    ["Karaoké", "Escape game"], ["Station de ski", "Station balnéaire"], ["Pôle Nord", "Antarctique"],
  ],
  "Pays & villes": [
    ["France", "Belgique"], ["Espagne", "Portugal"], ["Italie", "Grèce"],
    ["Allemagne", "Autriche"], ["Suisse", "Luxembourg"], ["Angleterre", "Irlande"],
    ["États-Unis", "Canada"], ["Mexique", "Brésil"], ["Argentine", "Chili"],
    ["Japon", "Corée du Sud"], ["Chine", "Inde"], ["Thaïlande", "Vietnam"],
    ["Maroc", "Tunisie"], ["Algérie", "Égypte"], ["Sénégal", "Côte d'Ivoire"],
    ["Australie", "Nouvelle-Zélande"], ["Russie", "Ukraine"], ["Suède", "Norvège"],
    ["Danemark", "Finlande"], ["Pays-Bas", "Danemark"], ["Islande", "Groenland"],
    ["Paris", "Londres"], ["New York", "Los Angeles"], ["Rome", "Venise"],
    ["Barcelone", "Madrid"], ["Marseille", "Nice"], ["Lyon", "Bordeaux"],
    ["Toulouse", "Montpellier"], ["Lille", "Strasbourg"], ["Nantes", "Rennes"],
    ["Tokyo", "Kyoto"], ["Dubaï", "Abu Dhabi"], ["Las Vegas", "Miami"],
    ["Berlin", "Munich"], ["Amsterdam", "Bruxelles"], ["Monaco", "Saint-Tropez"],
    ["Hawaï", "Tahiti"], ["Martinique", "Guadeloupe"], ["Corse", "Sardaigne"],
    ["Bretagne", "Normandie"],
  ],
  "Métiers": [
    ["Médecin", "Infirmier"], ["Dentiste", "Orthodontiste"], ["Pompier", "Policier"],
    ["Avocat", "Juge"], ["Professeur", "Instituteur"], ["Boulanger", "Pâtissier"],
    ["Cuisinier", "Serveur"], ["Pilote", "Hôtesse de l'air"], ["Plombier", "Électricien"],
    ["Maçon", "Charpentier"], ["Architecte", "Ingénieur"], ["Journaliste", "Écrivain"],
    ["Acteur", "Chanteur"], ["Danseur", "Mannequin"], ["Photographe", "Peintre"],
    ["Coiffeur", "Barbier"], ["Vétérinaire", "Éleveur"], ["Agriculteur", "Jardinier"],
    ["Facteur", "Livreur"], ["Chauffeur de taxi", "Chauffeur de bus"],
    ["Banquier", "Comptable"], ["Développeur", "Hacker"], ["Astronaute", "Astronome"],
    ["Scientifique", "Chercheur"], ["Pharmacien", "Chimiste"], ["Psychologue", "Coach"],
    ["Soldat", "Gendarme"], ["Espion", "Détective"], ["Pirate", "Corsaire"],
    ["Magicien", "Clown"], ["DJ", "Musicien"], ["Youtubeur", "Influenceur"],
    ["Caissier", "Vendeur"], ["Agent immobilier", "Notaire"], ["Sage-femme", "Pédiatre"],
    ["Maître-nageur", "Sauveteur"], ["Arbitre", "Entraîneur"], ["Moine", "Prêtre"],
    ["Bûcheron", "Menuisier"], ["Fleuriste", "Paysagiste"],
  ],
  "Sports & loisirs": [
    ["Football", "Rugby"], ["Basket", "Handball"], ["Tennis", "Badminton"],
    ["Ping-pong", "Squash"], ["Volley", "Beach-volley"], ["Golf", "Mini-golf"],
    ["Natation", "Plongée"], ["Surf", "Bodyboard"], ["Ski", "Snowboard"],
    ["Patin à glace", "Roller"], ["Skateboard", "Trottinette"], ["Vélo", "VTT"],
    ["Course à pied", "Marathon"], ["Boxe", "Karaté"], ["Judo", "Lutte"],
    ["Escrime", "Tir à l'arc"], ["Équitation", "Polo"], ["Escalade", "Randonnée"],
    ["Yoga", "Pilates"], ["Musculation", "CrossFit"], ["Danse", "Zumba"],
    ["Pétanque", "Bowling"], ["Billard", "Fléchettes"], ["Échecs", "Dames"],
    ["Poker", "Belote"], ["Uno", "Monopoly"], ["Scrabble", "Mots croisés"],
    ["Puzzle", "Lego"], ["Formule 1", "Rallye"], ["Moto", "Quad"],
    ["Parachute", "Parapente"], ["Saut à l'élastique", "Saut en parachute"],
    ["Kayak", "Aviron"], ["Voile", "Planche à voile"], ["Pêche", "Chasse"],
    ["Hockey", "Curling"], ["Baseball", "Cricket"], ["Jeu vidéo", "Jeu de société"],
    ["Karaoké", "Blind test"], ["Paintball", "Laser game"], ["Cache-cache", "Chat perché"],
    ["Sudoku", "Rubik's cube"], ["Jardinage", "Bricolage"], ["Tricot", "Couture"],
    ["Camping", "Glamping"], ["Pique-nique", "Barbecue"],
  ],
  "Transports": [
    ["Voiture", "Camion"], ["Bus", "Car"], ["Train", "TGV"], ["Avion", "Hélicoptère"],
    ["Bateau", "Sous-marin"], ["Voilier", "Yacht"], ["Paquebot", "Ferry"],
    ["Moto", "Scooter"], ["Vélo", "Tandem"], ["Taxi", "Uber"],
    ["Ambulance", "Camion de pompiers"], ["Fusée", "Navette spatiale"], ["Montgolfière", "Dirigeable"],
    ["Tracteur", "Moissonneuse"], ["Tank", "Jeep"], ["Calèche", "Carrosse"],
    ["Pirogue", "Canoë"], ["Jet-ski", "Hors-bord"], ["Téléphérique", "Télésiège"],
    ["Limousine", "Décapotable"], ["Camping-car", "Caravane"], ["Planeur", "ULM"],
    ["Trottinette électrique", "Hoverboard"], ["Luge", "Traîneau"], ["Gondole", "Radeau"],
  ],
  "Tech & internet": [
    ["iPhone", "Samsung"], ["Ordinateur", "Tablette"], ["Clavier", "Souris"],
    ["Écran", "Télévision"], ["Casque", "Écouteurs"], ["Enceinte", "Radio"],
    ["Instagram", "TikTok"], ["Snapchat", "BeReal"], ["Facebook", "Twitter"],
    ["WhatsApp", "Messenger"], ["YouTube", "Twitch"], ["Netflix", "Disney+"],
    ["Spotify", "Deezer"], ["Google", "Wikipédia"], ["Amazon", "eBay"],
    ["PlayStation", "Xbox"], ["Nintendo Switch", "Game Boy"], ["Wi-Fi", "Bluetooth"],
    ["Clé USB", "Disque dur"], ["Imprimante", "Scanner"], ["Selfie", "Photo de groupe"],
    ["Emoji", "GIF"], ["Mot de passe", "Code PIN"], ["Virus", "Bug"],
    ["Robot", "Drone"], ["Intelligence artificielle", "Algorithme"], ["Tinder", "Bumble"],
    ["Uber Eats", "Deliveroo"], ["Airbnb", "Booking"], ["Like", "Commentaire"],
    ["Story", "Reel"], ["Podcast", "Livre audio"], ["Appareil photo", "Caméra"],
    ["Montre connectée", "Bracelet fitness"], ["Bitcoin", "Ethereum"], ["Mail", "SMS"],
    ["Chargeur", "Batterie externe"], ["Zoom", "Teams"], ["Minecraft", "Roblox"],
    ["Fortnite", "Call of Duty"], ["Mario", "Sonic"], ["Pokémon", "Digimon"],
    ["Zelda", "Final Fantasy"], ["GTA", "Red Dead Redemption"], ["FIFA", "Rocket League"],
  ],
  "Cinéma & séries": [
    ["Harry Potter", "Le Seigneur des anneaux"], ["Star Wars", "Star Trek"],
    ["Marvel", "DC"], ["Batman", "Superman"], ["Spider-Man", "Iron Man"],
    ["Hulk", "Thor"], ["Wonder Woman", "Catwoman"], ["Joker", "Thanos"],
    ["Titanic", "Avatar"], ["Le Roi Lion", "Le Livre de la jungle"],
    ["La Reine des neiges", "Raiponce"], ["Shrek", "L'Âge de glace"],
    ["Toy Story", "Cars"], ["Nemo", "Dory"], ["Mickey", "Donald"],
    ["Blanche-Neige", "Cendrillon"], ["Aladdin", "Mulan"], ["Pinocchio", "Peter Pan"],
    ["Les Simpson", "Family Guy"], ["Bob l'éponge", "Les Razmoket"],
    ["Friends", "How I Met Your Mother"], ["Game of Thrones", "The Witcher"],
    ["Breaking Bad", "Narcos"], ["La Casa de Papel", "Lupin"],
    ["Stranger Things", "Dark"], ["Squid Game", "Alice in Borderland"],
    ["The Office", "Brooklyn Nine-Nine"], ["Grey's Anatomy", "Dr House"],
    ["Sherlock", "Columbo"], ["James Bond", "Mission impossible"],
    ["Fast & Furious", "Taxi"], ["Les Visiteurs", "Astérix"],
    ["Bienvenue chez les Ch'tis", "Intouchables"], ["OSS 117", "Kaamelott"],
    ["Pirates des Caraïbes", "Indiana Jones"], ["Jurassic Park", "King Kong"],
    ["Matrix", "Inception"], ["Terminator", "Robocop"], ["Rocky", "Creed"],
    ["Scream", "Halloween"], ["Dracula", "Frankenstein"], ["Zombie", "Vampire"],
    ["Fantôme", "Sorcière"], ["Gandalf", "Dumbledore"], ["Dark Vador", "Voldemort"],
    ["Naruto", "One Piece"], ["Dragon Ball", "Pokémon"], ["Totoro", "Le Voyage de Chihiro"],
    ["Oscar", "César"], ["Netflix and chill", "Soirée ciné"],
  ],
  "Musique": [
    ["Guitare", "Basse"], ["Piano", "Synthétiseur"], ["Violon", "Violoncelle"],
    ["Batterie", "Tambour"], ["Trompette", "Saxophone"], ["Flûte", "Clarinette"],
    ["Harpe", "Lyre"], ["Accordéon", "Harmonica"], ["Rap", "R'n'B"],
    ["Rock", "Métal"], ["Pop", "Électro"], ["Jazz", "Blues"], ["Reggae", "Ska"],
    ["Opéra", "Comédie musicale"], ["Concert", "Festival"], ["Chorale", "Fanfare"],
    ["Micro", "Haut-parleur"], ["Vinyle", "CD"], ["Beyoncé", "Rihanna"],
    ["Michael Jackson", "Elvis Presley"], ["Johnny Hallyday", "Michel Sardou"],
    ["Stromae", "Angèle"], ["Jul", "Naps"], ["PNL", "Nekfeu"], ["Aya Nakamura", "Wejdene"],
    ["Daft Punk", "David Guetta"], ["The Beatles", "The Rolling Stones"],
    ["Céline Dion", "Mylène Farmer"], ["Eminem", "50 Cent"], ["Taylor Swift", "Ed Sheeran"],
    ["Mozart", "Beethoven"], ["Eurovision", "The Voice"], ["Karaoké", "Playback"],
    ["Booba", "Kaaris"], ["Orelsan", "Bigflo & Oli"],
  ],
  "Corps & santé": [
    ["Main", "Pied"], ["Bras", "Jambe"], ["Genou", "Coude"], ["Œil", "Oreille"],
    ["Nez", "Bouche"], ["Dent", "Langue"], ["Cheveux", "Barbe"], ["Sourcil", "Cil"],
    ["Cœur", "Poumon"], ["Cerveau", "Crâne"], ["Estomac", "Ventre"], ["Os", "Muscle"],
    ["Doigt", "Orteil"], ["Ongle", "Griffe"], ["Épaule", "Hanche"], ["Nombril", "Grain de beauté"],
    ["Rhume", "Grippe"], ["Fièvre", "Migraine"], ["Toux", "Éternuement"],
    ["Pansement", "Plâtre"], ["Piqûre", "Vaccin"], ["Médicament", "Sirop"],
    ["Hoquet", "Bâillement"], ["Ronflement", "Somnambulisme"], ["Cauchemar", "Rêve"],
    ["Bouton", "Cicatrice"], ["Bleu", "Bosse"], ["Larme", "Sueur"],
    ["Fauteuil roulant", "Béquille"], ["Massage", "Kiné"],
  ],
  "Nature & météo": [
    ["Soleil", "Lune"], ["Étoile", "Planète"], ["Nuage", "Brouillard"],
    ["Pluie", "Neige"], ["Grêle", "Verglas"], ["Orage", "Tempête"],
    ["Éclair", "Tonnerre"], ["Arc-en-ciel", "Aurore boréale"], ["Vent", "Tornade"],
    ["Ouragan", "Tsunami"], ["Séisme", "Avalanche"], ["Été", "Printemps"],
    ["Hiver", "Automne"], ["Lever de soleil", "Coucher de soleil"], ["Rose", "Tulipe"],
    ["Marguerite", "Tournesol"], ["Arbre", "Buisson"], ["Sapin", "Palmier"],
    ["Chêne", "Bouleau"], ["Cactus", "Aloe vera"], ["Feuille", "Pétale"],
    ["Sable", "Gravier"], ["Rocher", "Caillou"], ["Glace", "Glacier"],
    ["Feu", "Braise"], ["Lave", "Magma"], ["Comète", "Météorite"], ["Mars", "Jupiter"],
    ["Galaxie", "Trou noir"], ["Vague", "Marée"],
  ],
  "Fêtes & événements": [
    ["Anniversaire", "Fête"], ["Mariage", "Fiançailles"], ["Noël", "Nouvel An"],
    ["Halloween", "Carnaval"], ["Pâques", "Toussaint"], ["Saint-Valentin", "Fête des mères"],
    ["Baptême", "Communion"], ["Enterrement de vie de garçon", "Enterrement de vie de jeune fille"],
    ["Crémaillère", "Apéro"], ["Soirée pyjama", "Soirée déguisée"], ["Bal", "Gala"],
    ["Feu d'artifice", "Pétard"], ["Cadeau", "Surprise"], ["Gâteau", "Bougie"],
    ["Ballon", "Confetti"], ["Sapin de Noël", "Crèche"], ["Père Noël", "Lutin"],
    ["Fête de la musique", "14 Juillet"], ["Brocante", "Vide-grenier"], ["Bac", "Permis"],
    ["Remise de diplôme", "Pot de départ"], ["Lune de miel", "Voyage de noces"],
    ["Ramadan", "Carême"], ["Nouvel An chinois", "Diwali"], ["Oktoberfest", "Fête de la bière"],
  ],
  "Personnalités": [
    ["Napoléon", "Louis XIV"], ["Jules César", "Cléopâtre"], ["Einstein", "Newton"],
    ["Mbappé", "Neymar"], ["Messi", "Ronaldo"], ["Zidane", "Platini"],
    ["Usain Bolt", "Michael Phelps"], ["Roger Federer", "Rafael Nadal"],
    ["Teddy Riner", "Tony Parker"], ["Victor Wembanyama", "LeBron James"],
    ["Elon Musk", "Jeff Bezos"], ["Steve Jobs", "Bill Gates"], ["Mark Zuckerberg", "Elon Musk"],
    ["Barack Obama", "Donald Trump"], ["Macron", "Sarkozy"], ["La reine d'Angleterre", "Lady Di"],
    ["Squeezie", "Cyprien"], ["Norman", "Mister V"], ["Inoxtag", "Michou"],
    ["Omar Sy", "Jamel Debbouze"], ["Kev Adams", "Gad Elmaleh"], ["Jean Dujardin", "Gilles Lellouche"],
    ["Brad Pitt", "Leonardo DiCaprio"], ["Kim Kardashian", "Paris Hilton"],
    ["Picasso", "Van Gogh"], ["Léonard de Vinci", "Michel-Ange"], ["Molière", "Victor Hugo"],
    ["Shakespeare", "Molière"], ["Jeanne d'Arc", "Marie Curie"], ["Cyril Hanouna", "Jean-Pierre Foucault"],
  ],
  "Fantastique & divers": [
    ["Sorcier", "Magicien"], ["Fée", "Elfe"], ["Nain", "Lutin"], ["Géant", "Ogre"],
    ["Sirène", "Triton"], ["Ange", "Démon"], ["Paradis", "Enfer"], ["Extraterrestre", "OVNI"],
    ["Robot", "Cyborg"], ["Super-héros", "Super-vilain"], ["Ninja", "Samouraï"],
    ["Chevalier", "Mousquetaire"], ["Roi", "Empereur"], ["Princesse", "Reine"],
    ["Cowboy", "Indien"], ["Viking", "Gladiateur"], ["Momie", "Squelette"],
    ["Loup-garou", "Yéti"], ["Baguette magique", "Balai volant"], ["Potion", "Sortilège"],
    ["Trésor", "Coffre"], ["Carte au trésor", "Boussole"], ["Épée", "Hache"],
    ["Arc", "Arbalète"], ["Bouclier", "Armure"], ["Couronne", "Diadème"],
    ["Pyramide", "Sphinx"], ["Tour Eiffel", "Statue de la Liberté"], ["Big Ben", "Colisée"],
    ["Muraille de Chine", "Machu Picchu"],
  ],
  "Vie quotidienne": [
    ["Petit-déjeuner", "Brunch"], ["Déjeuner", "Dîner"], ["Goûter", "Apéro"],
    ["Sieste", "Grasse matinée"], ["Douche", "Bain"], ["Ménage", "Vaisselle"],
    ["Courses", "Shopping"], ["Lessive", "Repassage"], ["Rendez-vous", "Réunion"],
    ["Vacances", "Week-end"], ["Lundi", "Vendredi"], ["Matin", "Soir"],
    ["Embouteillage", "Bouchon"], ["Retard", "Panne"], ["Facture", "Impôts"],
    ["Loyer", "Crédit"], ["Salaire", "Prime"], ["Télétravail", "Open space"],
    ["Examen", "Contrôle"], ["Devoirs", "Révisions"], ["Récréation", "Cantine"],
    ["Colocataire", "Voisin"], ["Meilleur ami", "Confident"], ["Ex", "Crush"],
    ["Premier rendez-vous", "Coup de foudre"], ["Dispute", "Rupture"], ["Bisou", "Câlin"],
    ["Mensonge", "Secret"], ["Rumeur", "Potin"], ["Blague", "Devinette"],
    ["Gueule de bois", "Lendemain de soirée"], ["Selfie", "Story"], ["Tatouage", "Henné"],
    ["Régime", "Jeûne"], ["Insomnie", "Fatigue"], ["Déménagement", "Emménagement"],
    ["Bébé", "Enfant"], ["Grand-mère", "Grand-père"], ["Oncle", "Cousin"],
    ["Mariage", "PACS"], ["Chômage", "Retraite"], ["Stage", "Alternance"],
  ],
};
